### ISSUE TITLE
Access Management

### ISSUE THREAD

**Issue by shemsargent-rvtd** [RVTD/RideTeam#102]
# Access Management overview
Allows creation and modification of user permission and roles. User roles comprise sets of permissions. Each user may be assigned one or more roles. A permission in the system is assumed to not apply to a user unless it is added to a role that is assigned to the user.
# Default Roles and Permissions
* Software Developer
* System Administrator
* Brokerage Manager
* Brokerage Supervisor
* Brokerage CSR
* Brokerage Scheduler
* Brokerage Billing Coordinator
* Brokerage Quality Assurance Coordinator
* Provider Manager
* Provider Dispatcher
* Provider CSR
* Facility Manager
* Facility Staff
* Member
* Member Proxy
* Medicaid Reimbursement Recipient
# Nonstandard Roles
Example: User is assigned the standard Brokerage CSR role. Management wishes to extend one or more permissions to the User that are normally assigned to a Brokerage Scheduler, but do not wish for User to have all the permissions of a Brokerage Scheduler. The best practice is to create a new Role with a descriptive name like 'Brokerage Scheduler Assistant' or 'Brokerage Bus Ticket Coordinator'. The new Role can have just the few necessary permissions added to it and then this Role can be applied to the User in addition to the existing Brokerage CSR permission.
# Full List of Permissions
**Current full permission string:** -cm,-rm,-um,-dm,-cr,-rr,-ur,-dr,-cf,-rf,-uf,-df,-csip,-rsip,-usip,-dsip,-cu,-ru,-uu,-du,-csrpmd,-csrpml,-pul,-pud,-csrpbt,-csrpre,-schpml,-schpmd,-schprl,-schprd,-schpgr,-comppr,-compfa,-comdas,-quapsi,-quapme,-admuse,-admdas,-admpar,-cp,-rp,-up,-dp,-ctv,-rtv,-utv,-dtv,-rme
**Description of mnemonics:**
    rtv	Read Table Views
    rf	Read Facilities
    cf	Create Facilities
    uf	Update Facilities
    rp	Read Providers
    rm	Read Members
    cm	Create Members
    um	Update Members
    rr	Read Rides
    cr	Create Rides
    ur	Update Rides
    cu	Create Users
    uu	Update Users
    quapme	read mobility evaluations, mobility_evaluation/add, mobility_evaluation/edit
    rme	post member eligibility
    comdas	Common Dashboard
    csrpmd && csrpml	CSR Booking, Account
    csrpbt	CSR Bus Tickets
    csrpre	CSR Reimbursement
    schpml && schpmd	Schedule Members
    schprl && schprd	Scheduling Ride Groups
    scgpgr	Scheduling Grid
    compfa	Common Facilities
    comppr	common_providers, reimbursement_payees, reimbursement_payees/add, reimbursement_payees/edit
    quapsi	QA SIPs
    admuse	admin_users
    admdas	admin_dashboard
    admpar	admin_parameters

# Objective of this ticket
The current permissions listed above need to be converted to a table that will not be editable by any users. It is only intended to be modified by developers. Additional permissions will be added by developers as the software usage expands.
**auth_permission** (auto id, string permission_name, string permission_description)

Additional tables will be used to associate permissions to roles and roles to users. These tables will be modifiable by users with appropriate permission
**auth_user_role** (auto id, int user_id, int auth_role_id) + standard change tracking fields
**auth_role** (auto id, string role_name, string role_details) + standard change tracking fields
**auth_role_permission** (auto id, int auth_role_id, auth_permission_id) + standard change tracking fields

A basic wrapper function can be used to determine if a user has a particular permission. The wrapper function can execute a query on demand that joins these tables and compare the required permission with the available permission.

**Comment by sclark-rvtd** [comment]
Since we have cases where users will have permission to view/edit/create/delete their own content, but not that of others, this needs to be a little bit different than described..

**Comment by sclark-rvtd** [comment]
Pull request: https://github.com/RVTD/RideTeam/pull/129  Closing this issue in favor of opening individual issues for pages required to manage users.
