### ISSUE TITLE
Session Timeout Notification

### ISSUE THREAD

**Issue by mchristensen-rvtd** [RVTD/RideTeam#166]
Need to implement some sort of session timeout notification.

**Comment by sclark-rvtd** [comment]
related to #168

**Comment by sclark-rvtd** [comment]
Pull request https://github.com/RVTD/RideTeam/pull/171

**Comment by sclark-rvtd** [comment]
@mchristensen-rvtd Do you want to take a look?

**Comment by sclark-rvtd** [comment]
merged, closing
