### ISSUE TITLE
Member Eligibility is not showing up on the members page

### ISSUE THREAD

**Issue by sclark-rvtd** [RVTD/RideTeam#2]
This may be partly a db migration problem the member_eligibility table is missing the members id.

![missing_eligibility](https://user-images.githubusercontent.com/34458007/34001496-0082f5c2-e0a5-11e7-934a-2e63e3751819.png)

**Comment by shemsargent-rvtd** [comment]
OBSS does not have the clientID in the clientelig table. It appears that the migration process is not looking up the member_id value from the member_funding table and and adding it to the member_eligibility records.

**Comment by shemsargent-rvtd** [comment]
In the member search results, I would like to see the Medicaid CCO in red or green depending on last eligibility check result or black if none, followed by the Non-Medicaid funding sources all in black. The full list can be space separated.

This query shows this data separated out in a logical way.

```
SELECT 
m.first_name,
m.last_name,
m.dob,
group_concat(DISTINCT cco.code SEPARATOR ' ') as `Eligible CCO`,
group_concat(DISTINCT mf.prime SEPARATOR ' ') as Primes,
group_concat(case fs.funding_source_type_id when 1 then null else fs.code end SEPARATOR ' ') as `Non-Medicaid Funding`,
group_concat(case fs.funding_source_type_id when 2 then null else fs.code end SEPARATOR ' ') as `Medicaid Funding`,
group_concat(DISTINCT export_set(me.eligible,'Yes','No','',1) SEPARATOR ' ') as `Eligibile with Brokerage`, 
group_concat(DISTINCT me.last_update SEPARATOR ' ') as `Last Check` 
FROM 
member as m
left join
member_funding as mf
on m.id = mf.member_id
left join
funding_source as fs
on mf.funding_source = fs.id
left join 
member_eligibility as me
on mf.prime = me.prime
left join
cco
on me.cco=cco.name
#where fs.funding_source_type_id >1
group by m.id,me.prime
order by m.last_name,m.first_name,fs.code;
```

**Comment by sclark-rvtd** [comment]
Note:  If someone's address changes, a popup comes up and the call center will verify the address of the client on the phone.  When this is implemented, it needs to be tested by changing a member's address on the RideTeam database.  A state verification will have to be triggered.

**Comment by sclark-rvtd** [comment]
Pull Request: https://github.com/RVTD/RideTeam/pull/9
